apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
spec:
  hard:
    pods: "2" 
    requests.cpu: "1" 
    requests.memory: "500Mi"
    requests.storage: "50Gi"
    limits.cpu: "2" 
    limits.memory: "2Gi" 
    persistentvolumeclaims: "1" 
    openshift.io/imagestreams: "5"
    secrets: "5"
    configmaps: "5"